
# Default config

# Set default language
languageCode: "en-gb"

# Site title, copyright, and author
title: "Rowan Manning"
copyright: "Copyright © {year}, Rowan Manning"
author:
  name: "Rowan Manning"
  url: "https://rowanmanning.com/"
  image: "https://rowanmanning.com/about/rowan.png"
  github: "rowanmanning"
  mastodon: "https://hachyderm.io/@rowan"
  twitter: "rowanmanning"

# Configure the themes
theme:
  - rowanmanning

# We only want the tags taxonomy
taxonomies:
  tag: "tags"

# Simplify the permalinks for blog posts
permalinks:
  posts: "/posts/:filename/"
  weeknotes: "/weeknotes/:filename/"

# Enable emoji rendering
enableEmoji: true

# Use classes for syntax highlighting
markup:
  highlight:
    noClasses: false

# Restrict the output of RSS feeds, and add ATOM feeds for sections
outputs:
  home: ["HTML", "ATOM", "LUNR"]
  page: ["HTML"]
  section: ["HTML", "ATOM"]
  taxonomy: ["HTML"]
  term: ["HTML"]

# Publish to the "build" directory
publishDir: "build"

# Set a long timeout so that image-heavy pages can build
timeout: 5m

# Configure related content
related:
  includeNewer: true
  indices:
    - name: tags
      weight: 80
    - name: date
      weight: 10
  threshold: 80
  toLower: false

# Site parameters
params:

  # Further related content configuration
  relatedContent:
    enabled: true
    count: 3
    allowTypes:
      - posts
      - weeknotes

  # Webmention configuration
  webmention:
    enabled: true
    receiver: "https://webmention.io/rowanmanning.com/webmention"

  # Pingback configurations
  pingback:
    enabled: true
    receiver: "https://webmention.io/rowanmanning.com/xmlrpc"

  # Structured data configurations
  structuredData:
    enabled: true

  # Pagination configuration
  pagination:
    enabled: true
    perPage: 20

  # Home page hero configurations
  # hero:
  #   backgroundColorTop: "red"
  #   backgroundColorBottom: "yellow"
  #   textColor: "blue"

  # Configure the home page feed
  feedSections:
    - notes
    - posts
    - weeknotes

# Security config
security:
  funcs:
    getenv:
      - ^HUGO_
      - NOTE_REF_URL
