
# Atom Feed
# =========
#
# Add "ATOM" to any Page Kind under [outputs] in your site config
# to generate an Atom feed.
#
# Example:
#   [outputs]
#     home = ["HTML", "ATOM"]

# Required media types
[mediaTypes."application/atom+xml"]
  suffixes = ["xml"]

# Atom output formats
# https://validator.w3.org/feed/docs/atom.html#whatIsAtom
[outputFormats.Atom]
  name = "Atom"
  mediaType = "application/atom+xml"
  baseName = "feed"
  isPlainText = false
  rel = "alternate"
  isHTML = false
  noUgly = true
  permalinkable = false

# Lunr Index
# ==========
#
# Add "LUNR" to the home Page Kind under [outputs.home] in your site config
# to generate a Lunr index.
#
# Example:
#   [outputs]
#     home = ["HTML", "LUNR"]

# Required media types
[mediaTypes."application/json"]
  suffixes = ["lunr.json"]

# Lunr output formats (generates the document list)
# https://lunrjs.com/guides/getting_started.html#creating-an-index
[outputFormats.Lunr]
  name = "Lunr"
  mediaType = "application/json"
  baseName = "index"
  isPlainText = true
  rel = "alternate"
  isHTML = false
  noUgly = false
  permalinkable = false
