
# Config for production environment

# Set the base URL
baseURL: https://rowanmanning.com/

# Set up site analytics
params:
  analytics:
    fathomSiteId: "LZDRDPSO"
    fathomSiteHostname: "falcon.rowanmanning.com"
    fathomGoalIds:
      feedView: "BPV3BBHK"
      search: "BQDXHKN1"
      webmentionSend: "YLQQARGU"
