
# Config for production environment

# Set the base URL
baseURL: https://rowanmanning.com/


# Site parameters
params:

  # Analytics configuration
  fathom:
    siteId: "LZDRDPSO"
    siteHostname: "falcon.rowanmanning.com"
    goalIds:
      feedView: "BPV3BBHK"
      search: "BQDXHKN1"
      webmentionSend: "YLQQARGU"
