
# Config for production environment

# Set the base URL
# baseURL: https://rowanmanning.com/
baseURL: https://rowanmanning.github.io/rowanmanning.com/

# Set up site analytics
params:
  analytics:
    fathomSiteId: "LZDRDPSO"
