
name: Build and deploy
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

on:

  # Run when the main branch is pushed or a pull request is made
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Run when webmentions are fetched
  workflow_run:
    workflows:
      - Fetch webmentions
    branches:
      - main
    types:
      - completed

# Jobs
jobs:

  # Install dependencies
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules-v1
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Node.js dependencies
        run: npm install

  # Build website
  build:
    name: Build the website
    runs-on: ubuntu-latest
    needs: install
    steps:

      - name: Checkout with submodules
        uses: actions/checkout@v2
        with:
          submodules: true # Install themes
          fetch-depth: 0 # We need all history for .GitInfo and .Lastmod

      - name: Restore node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules-v1
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Cache built website
        uses: actions/cache@v3
        env:
          cache-name: cache-website-v1
        with:
          path: |
            build
            resources/_gen
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('config', 'content', 'data', 'themes') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.97.3"
          extended: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Configure timezone as Europe/London
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Europe/London

      - name: Build the website
        run: npm run build

  # Verify code
  verify:
    name: Verify JavaScript
    runs-on: ubuntu-latest
    needs: install
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules-v1
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Verify code
        run: npm run verify

  # Run theme tests
  test-themes:
    name: Run theme tests
    runs-on: ubuntu-latest
    needs: install
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules-v1
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.97.3"
          extended: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Run tests
        run: npm run test

  # Deploy to GitHub Pages production (only on main branch)
  deploy-production:
    name: Deploy to production
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    if: github.ref == 'refs/heads/main'
    needs:
      - build
      - verify
      - test-themes
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore built website
        uses: actions/cache@v3
        env:
          cache-name: cache-website-v1
        with:
          path: |
            build
            resources/_gen
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('config', 'content', 'data', 'themes') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Setup GitHub Pages
        id: pages
        uses: actions/configure-pages@v1

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
