
name: Build and deploy staging
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:

  # Run when the main branch is pushed
  push:
    branches:
      - main

  # Run when webmentions are fetched
  workflow_run:
    workflows:
      - Fetch webmentions
    branches:
      - main
    types:
      - completed

# Jobs
jobs:

  # Build website
  build:
    name: Build the website
    runs-on: ubuntu-latest
    steps:

      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          submodules: true # Install themes
          fetch-depth: 0 # We need all history for .GitInfo and .Lastmod

      - name: Cache node modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules-v1
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Cache built website
        uses: actions/cache@v4
        env:
          cache-name: cache-staging-website-v1
        with:
          path: |
            build
            resources/_gen
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('config', 'content', 'data', 'themes') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.101.0"
          extended: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node.js dependencies
        run: npm install

      - name: Configure timezone as Europe/London
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Europe/London

      - name: Build the staging website
        run: npm run build-staging

  # Deploy to GitHub Pages staging (only on main branch)
  deploy-production:
    name: Deploy to staging
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Restore built website
        uses: actions/cache@v4
        env:
          cache-name: cache-staging-website-v1
        with:
          path: |
            build
            resources/_gen
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('config', 'content', 'data', 'themes') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.DEPLOY_KEY }}
          user_name: 'RowBot'
          user_email: '48598026+rowanbot@users.noreply.github.com'
          external_repository: rowanmanning/drafts.rowanmanning.com
          publish_dir: ./build
          publish_branch: build
          cname: drafts.rowanmanning.com
