
name: Fetch webmentions

# Run every 30 minutes
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: {}

# Jobs
jobs:
  webmentions:
    runs-on: ubuntu-18.04
    steps:

      - uses: actions/checkout@v2

      # Set up Node.js and install dependencies
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions/cache@v1
        env:
          cache-version: v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-version }}-
            ${{ runner.os }}-
      - run: npm install

      # Fetch and process webmentions
      - name: Fetch webmentions
        env:
          WEBMENTION_API_KEY: ${{ secrets.WEBMENTION_API_KEY }}
        run: make fetch-webmentions

      # Commit new webmentions to the repo
      - name: Commit to the repo
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          git config --global user.name "RowBot"
          git config --global user.email "48598026+rowanbot@users.noreply.github.com"
          git remote set-url origin "https://rowanbot:${DEPLOY_KEY}@github.com/${GITHUB_REPOSITORY}.git"
          git checkout main
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Fetch webmentions"; git push origin main)
