
name: Publish to GitHub Pages (Staging)

# Run when the main branch is pushed
on:
  push:
    branches:
      - main
  workflow_run:
    workflows:
      - Fetch webmentions
    branches:
      - main
    types:
      - completed

# Jobs
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:

      - uses: actions/checkout@v2
        with:
          submodules: true # To install themes
          fetch-depth: 0 # We need all history for .GitInfo and .Lastmod

      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Europe/London

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.76.5"
          extended: true

      - name: Build
        run: hugo --minify --environment staging

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DEPLOY_KEY }}
          external_repository: rowanmanning/drafts.rowanmanning.com
          publish_dir: ./build
          publish_branch: build
          cname: drafts.rowanmanning.com
