
name: Publish to GitHub Pages

# Run when the main branch is pushed
on:
  push:
    branches:
      - main
  workflow_run:
    workflows:
      - Fetch webmentions
    branches:
      - main
    types:
      - completed

# Jobs
jobs:

  # Verify code
  verify:
    name: Verify code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions/cache@v2
        env:
          cache-version: v2
        with:
          path: |
            ~/.npm
            /tmp/hugo_cache
          key: ${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('**/go.sum') }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-version }}-
            ${{ runner.os }}-
      - run: npm install
      - run: make verify

  # Run theme tests
  test-themes:
    name: Run theme tests
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions/cache@v2
        env:
          cache-version: v2
        with:
          path: |
            ~/.npm
            /tmp/hugo_cache
          key: ${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('**/go.sum') }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-version }}-
            ${{ runner.os }}-
      - run: npm install
      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.86.0"
          extended: true
      - run: make test-theme

  # Deploy to GitHub Pages
  deploy:
    name: Deploy Production
    needs: test-themes
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          submodules: true # To install themes
          fetch-depth: 0 # We need all history for .GitInfo and .Lastmod

      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Europe/London

      # Set up Node.js and install dependencies
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions/cache@v2
        env:
          cache-version: v2
        with:
          path: |
            ~/.npm
            /tmp/hugo_cache
          key: ${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('**/go.sum') }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-version }}-
            ${{ runner.os }}-
      - run: npm install

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.86.0"
          extended: true

      - name: Build
        run: make build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DEPLOY_KEY }}
          publish_dir: ./build
          publish_branch: build
          cname: rowanmanning.com
