
name: Publish to GitHub Pages

on:

  # Run on pushes targeting the default branch
  push:
    branches:
      - main
  
  # Run after webmentions have been fetched
  workflow_run:
    workflows:
      - Fetch webmentions
    branches:
      - main
    types:
      - completed

  # Allow manual workflow dispatch
  workflow_dispatch:


# Set the GITHUB_TOKEN permissions to allow deployment
# to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: pages
  cancel-in-progress: true

# Jobs
jobs:

  # Verify code
  verify:
    name: Verify code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/cache@v2
        env:
          cache-version: v2
        with:
          path: |
            ~/.npm
            /tmp/hugo_cache
          key: ${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('**/go.sum') }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-version }}-
            ${{ runner.os }}-
      - name: Install npm dependencies
        run: npm install
      - run: make verify

  # Run theme tests
  test-themes:
    name: Run theme tests
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/cache@v2
        env:
          cache-version: v2
        with:
          path: |
            ~/.npm
            /tmp/hugo_cache
          key: ${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('**/go.sum') }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-version }}-
            ${{ runner.os }}-
      - name: Install npm dependencies
        run: npm install
      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.97.3"
          extended: true
      - run: make test-theme

  # Deploy to GitHub Pages
  deploy:
    name: Deploy Production
    needs: test-themes
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true # To install themes
          fetch-depth: 0 # We need all history for .GitInfo and .Lastmod

      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Europe/London

      # Set up Node.js and install dependencies
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/cache@v2
        env:
          cache-version: v2
        with:
          path: |
            ~/.npm
            /tmp/hugo_cache
          key: ${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('**/go.sum') }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-version }}-
            ${{ runner.os }}-
      - name: Install npm dependencies
        run: npm install

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.97.3"
          extended: true

      - name: Build
        run: make build

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v1

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build
